I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/chapter_one.rpy", line 563, in script
    if flag==1:
  File "game/chapter_one.rpy", line 563, in <module>
    if flag==1:
NameError: name 'flag' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/chapter_one.rpy", line 563, in script
    if flag==1:
  File "D:\renpy\renpy-8.1.3-sdk\renpy\ast.py", line 2133, in execute
    if renpy.python.py_eval(condition):
  File "D:\renpy\renpy-8.1.3-sdk\renpy\python.py", line 1153, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "D:\renpy\renpy-8.1.3-sdk\renpy\python.py", line 1146, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/chapter_one.rpy", line 563, in <module>
    if flag==1:
NameError: name 'flag' is not defined

Windows-10-10.0.22621 AMD64
Ren'Py 8.1.3.23091805
CatMars 1.0
Tue Dec 26 20:09:21 2023
